return {

	"williamboman/mason.nvim",
	opts = {
		ensure_installed = {
			"stylua",
			"shfmt",
			"emmet-ls",
			"asm-lsp",
			"asmfmt",
			"stimulus-language-server",
			"actionlint",
			"ansible-language-server",
			"ansible-lint",
			"antlers-language-server",
			"black",
			"bash-language-server",
			"blade-formatter",
			"docker-compose-language-service",
			"dockerfile-language-server",
			"dot-language-server",
			"emmet-ls",
			"eslint_d",
			"flake8",
			"hadolint",
			"html-lsp",
			"intelephense",
			"nginx-language-server",
			"php-debug-adapter",
			"phpstan",
			"pint",
			"prettierd",
			"pyright",
			"rustywind",
			"shellcheck",
			"shfmt",
			"stylua",
			"tailwindcss-language-server",
		},
	},
}
